#!/bin/sh

R_BASE=/var/shared/rotated-logs

HL_DIR=/var/shared/archive/host-logs
HLK_DIR=/var/shared/archive/host-logs-kvp

rsync -rltgoDvz --rsh=ssh sysadmin@pomegranate.mapofmedicine.com:$R_BASE/* $HL_DIR
rsync -rltgoDvz --rsh=ssh sysadmin@pomegranate.mapofmedicine.com:$R_BASE/* $HLK_DIR
